/**
 * 开发接口代理
 * Generated By vue.config.js,Based on /config/webpack.proxy.js
*/

const API_SERVER = 'https://test.com'

module.exports = {
  // 接口代理
  '^/api': {
    target: API_SERVER,
    pathRewrite: { '/api': '/' },
    changeOrigin: true
  }
}